// Simple English to Urdu Translation Dictionary
const englishToUrduDict: { [key: string]: string } = {
  // Common words
  'the': 'یہ',
  'and': 'اور',
  'or': 'یا',
  'a': 'ایک',
  'an': 'ایک',
  'is': 'ہے',
  'are': 'ہیں',
  'was': 'تھا',
  'were': 'تھے',
  'will': 'گا',
  'would': 'گا',
  'can': 'سکتا',
  'could': 'سکتا',
  'should': 'چاہیے',
  'must': 'لازمی',
  'have': 'ہے',
  'has': 'ہے',
  'had': 'تھا',
  'do': 'کرنا',
  'does': 'کرتا',
  'did': 'کیا',
  'be': 'ہونا',
  'been': 'ہوا',
  'being': 'ہونا',
  'this': 'یہ',
  'that': 'وہ',
  'these': 'یہ',
  'those': 'وہ',
  'i': 'میں',
  'you': 'آپ',
  'he': 'وہ',
  'she': 'وہ',
  'it': 'یہ',
  'we': 'ہم',
  'they': 'وہ',
  'my': 'میرا',
  'your': 'آپ کا',
  'his': 'اس کا',
  'her': 'اس کا',
  'its': 'اس کا',
  'our': 'ہمارا',
  'their': 'ان کا',
  
  // Common verbs
  'go': 'جانا',
  'come': 'آنا',
  'get': 'لینا',
  'make': 'بنانا',
  'see': 'دیکھنا',
  'know': 'جاننا',
  'think': 'سوچنا',
  'take': 'لینا',
  'give': 'دینا',
  'work': 'کام',
  'say': 'کہنا',
  'tell': 'بتانا',
  'ask': 'پوچھنا',
  'help': 'مدد',
  'find': 'ملنا',
  'try': 'کوشش',
  'use': 'استعمال',
  'want': 'چاہنا',
  'need': 'ضرورت',
  'like': 'پسند',
  'love': 'محبت',
  'read': 'پڑھنا',
  'write': 'لکھنا',
  'understand': 'سمجھنا',
  'learn': 'سیکھنا',
  'teach': 'سکھانا',
  'study': 'مطالعہ',
  'play': 'کھیلنا',
  'eat': 'کھانا',
  'drink': 'پینا',
  'sleep': 'سونا',
  'walk': 'چلنا',
  'run': 'دوڑنا',
  'live': 'رہنا',
  'die': 'مرنا',
  'buy': 'خریدنا',
  'sell': 'بیچنا',
  'speak': 'بولنا',
  'listen': 'سننا',
  'look': 'دیکھنا',
  'watch': 'دیکھنا',
  'feel': 'محسوس',
  'become': 'بننا',
  'seem': 'لگنا',
  'keep': 'رکھنا',
  'leave': 'چھوڑنا',
  'stay': 'رہنا',
  'move': 'ہلنا',
  'stop': 'رکنا',
  'start': 'شروع',
  'begin': 'شروع',
  'end': 'ختم',
  'finish': 'ختم',
  'continue': 'جاری',
  'change': 'تبدیل',
  'turn': 'موڑنا',
  'open': 'کھولنا',
  'close': 'بند',
  'meet': 'ملنا',
  'follow': 'پیروی',
  'call': 'بلانا',
  'talk': 'بات',
  'discuss': 'بحث',
  
  // Common nouns
  'time': 'وقت',
  'day': 'دن',
  'night': 'رات',
  'week': 'ہفتہ',
  'month': 'مہینہ',
  'year': 'سال',
  'hour': 'گھنٹہ',
  'minute': 'منٹ',
  'second': 'سیکنڈ',
  'morning': 'صبح',
  'afternoon': 'دوپہر',
  'evening': 'شام',
  'today': 'آج',
  'tomorrow': 'کل',
  'yesterday': 'کل',
  'person': 'شخص',
  'people': 'لوگ',
  'man': 'آدمی',
  'woman': 'عورت',
  'child': 'بچہ',
  'boy': 'لڑکا',
  'girl': 'لڑکی',
  'family': 'خاندان',
  'friend': 'دوست',
  'house': 'گھر',
  'home': 'گھر',
  'place': 'جگہ',
  'world': 'دنیا',
  'country': 'ملک',
  'city': 'شہر',
  'town': 'قصبہ',
  'area': 'علاقہ',
  'school': 'سکول',
  'university': 'یونیورسٹی',
  'college': 'کالج',
  'office': 'دفتر',
  'company': 'کمپنی',
  'business': 'کاروبار',
  'government': 'حکومت',
  'money': 'پیسہ',
  'food': 'کھانا',
  'water': 'پانی',
  'book': 'کتاب',
  'paper': 'کاغذ',
  'car': 'گاڑی',
  'phone': 'فون',
  'computer': 'کمپیوٹر',
  'internet': 'انٹرنیٹ',
  'website': 'ویب سائٹ',
  'information': 'معلومات',
  'news': 'خبریں',
  'story': 'کہانی',
  'problem': 'مسئلہ',
  'question': 'سوال',
  'answer': 'جواب',
  'idea': 'خیال',
  'way': 'راستہ',
  'method': 'طریقہ',
  'system': 'نظام',
  'service': 'خدمت',
  'product': 'پروڈکٹ',
  'result': 'نتیجہ',
  'effect': 'اثر',
  'reason': 'وجہ',
  'cause': 'سبب',
  'purpose': 'مقصد',
  'goal': 'ہدف',
  'plan': 'منصوبہ',
  'project': 'پروجیکٹ',
  'program': 'پروگرام',
  'research': 'تحقیق',
  'analysis': 'تجزیہ',
  'report': 'رپورٹ',
  'data': 'ڈیٹا',
  'technology': 'ٹیکنالوجی',
  'science': 'سائنس',
  'health': 'صحت',
  'education': 'تعلیم',
  'culture': 'ثقافت',
  'language': 'زبان',
  'art': 'فن',
  'music': 'موسیقی',
  'sport': 'کھیل',
  'film': 'فلم',
  'photo': 'تصویر',
  
  // Common adjectives
  'good': 'اچھا',
  'bad': 'برا',
  'big': 'بڑا',
  'small': 'چھوٹا',
  'large': 'بڑا',
  'little': 'چھوٹا',
  'long': 'لمبا',
  'short': 'چھوٹا',
  'high': 'اونچا',
  'low': 'نیچا',
  'new': 'نیا',
  'old': 'پرانا',
  'young': 'جوان',
  'early': 'جلدی',
  'late': 'دیر',
  'fast': 'تیز',
  'slow': 'آہستہ',
  'hot': 'گرم',
  'cold': 'ٹھنڈا',
  'warm': 'گرم',
  'cool': 'ٹھنڈا',
  'easy': 'آسان',
  'difficult': 'مشکل',
  'hard': 'مشکل',
  'simple': 'آسان',
  'complex': 'پیچیدہ',
  'important': 'اہم',
  'special': 'خاص',
  'common': 'عام',
  'popular': 'مقبول',
  'famous': 'مشہور',
  'local': 'مقامی',
  'national': 'قومی',
  'international': 'بین الاقوامی',
  'public': 'عوامی',
  'private': 'نجی',
  'free': 'مفت',
  'available': 'دستیاب',
  'possible': 'ممکن',
  'impossible': 'ناممکن',
  'necessary': 'ضروری',
  'different': 'مختلف',
  'same': 'ویسا',
  'similar': 'ملتا جلتا',
  'beautiful': 'خوبصورت',
  'nice': 'اچھا',
  'great': 'بہترین',
  'excellent': 'بہترین',
  'perfect': 'کامل',
  'correct': 'صحیح',
  'wrong': 'غلط',
  'true': 'سچ',
  'false': 'جھوٹ',
  'real': 'حقیقی',
  'right': 'صحیح',
  'left': 'بائیں',
  'full': 'بھرا',
  'empty': 'خالی',
  'opened': 'کھلا',
  'closed': 'بند',
  'clear': 'صاف',
  'dark': 'اندھیرا',
  'light': 'روشنی',
  'heavy': 'بھاری',
  'strong': 'مضبوط',
  'weak': 'کمزور',
  'safe': 'محفوظ',
  'dangerous': 'خطرناک',
  'clean': 'صاف',
  'dirty': 'گندا',
  'healthy': 'صحت مند',
  'sick': 'بیمار',
  'rich': 'امیر',
  'poor': 'غریب',
  'expensive': 'مہنگا',
  'cheap': 'سستا',
  'modern': 'جدید',
  'traditional': 'روایتی',
  'normal': 'عام',
  'natural': 'قدرتی',
  'artificial': 'مصنوعی',
  'digital': 'ڈیجیٹل',
  'online': 'آن لائن',
  'social': 'سماجی',
  'political': 'سیاسی',
  'economic': 'اقتصادی',
  'financial': 'مالی',
  'medical': 'طبی',
  'legal': 'قانونی',
  'personal': 'ذاتی',
  'professional': 'پیشہ ورانہ',
  'academic': 'تعلیمی',
  'technical': 'تکنیکی',
  'scientific': 'سائنسی',
  'historical': 'تاریخی',
  'cultural': 'ثقافتی',
  'environmental': 'ماحولیاتی',
  'global': 'عالمی',
  'regional': 'علاقائی'
};

export function translateToUrdu(text: string): string {
  // Split text into words and translate each word
  const words = text.toLowerCase().match(/\b\w+\b/g) || [];
  const translatedWords = words.map(word => {
    return englishToUrduDict[word] || word;
  });
  
  // Join translated words back together
  let translatedText = translatedWords.join(' ');
  
  // Keep original punctuation structure roughly
  const punctuation = text.match(/[.,!?;:()]/g) || [];
  punctuation.forEach((punct, index) => {
    if (index < translatedWords.length) {
      translatedText += punct;
    }
  });
  
  return translatedText;
} 