// Simple English to Urdu Translation Dictionary
const englishToUrduDict: { [key: string]: string } = {
  // Common words
  'the': 'یہ',
  'and': 'اور',
  'or': 'یا',
  'a': 'ایک',
  'an': 'ایک',
  'is': 'ہے',
  'are': 'ہیں',
  'was': 'تھا',
  'were': 'تھے',
  'will': 'گا',
  'would': 'گا',
  'can': 'سکتا',
  'could': 'سکتا',
  'should': 'چاہیے',
  'must': 'لازمی',
  'have': 'ہے',
  'has': 'ہے',
  'had': 'تھا',
  'do': 'کرنا',
  'does': 'کرتا',
  'did': 'کیا',
  'be': 'ہونا',
  'been': 'ہوا',
  'being': 'ہونا',
  'this': 'یہ',
  'that': 'وہ',
  'these': 'یہ',
  'those': 'وہ',
  'i': 'میں',
  'you': 'آپ',
  'he': 'وہ',
  'she': 'وہ',
  'it': 'یہ',
  'we': 'ہم',
  'they': 'وہ',
  'my': 'میرا',
  'your': 'آپ کا',
  'his': 'اس کا',
  'her': 'اس کا',
  'its': 'اس کا',
  'our': 'ہمارا',
  'their': 'ان کا',
  
  // Common verbs
  'go': 'جانا',
  'come': 'آنا',
  'get': 'لینا',
  'make': 'بنانا',
  'see': 'دیکھنا',
  'know': 'جاننا',
  'think': 'سوچنا',
  'take': 'لینا',
  'give': 'دینا',
  'work': 'کام',
  'say': 'کہنا',
  'tell': 'بتانا',
  'ask': 'پوچھنا',
  'help': 'مدد',
  'find': 'ملنا',
  'try': 'کوشش',
  'use': 'استعمال',
  'want': 'چاہنا',
  'need': 'ضرورت',
  'like': 'پسند',
  'love': 'محبت',
  'read': 'پڑھنا',
  'write': 'لکھنا',
  'understand': 'سمجھنا',
  'learn': 'سیکھنا',
  'teach': 'سکھانا',
  'study': 'مطالعہ',
  'play': 'کھیلنا',
  'eat': 'کھانا',
  'drink': 'پینا',
  'sleep': 'سونا',
  'walk': 'چلنا',
  'run': 'دوڑنا',
  'live': 'رہنا',
  'die': 'مرنا',
  'buy': 'خریدنا',
  'sell': 'بیچنا',
  'speak': 'بولنا',
  'listen': 'سننا',
  'look': 'دیکھنا',
  'watch': 'دیکھنا',
  'feel': 'محسوس',
  'become': 'بننا',
  'seem': 'لگنا',
  'keep': 'رکھنا',
  'leave': 'چھوڑنا',
  'stay': 'رہنا',
  'move': 'ہلنا',
  'stop': 'رکنا',
  'start': 'شروع',
  'begin': 'شروع',
  'end': 'ختم',
  'finish': 'ختم',
  'continue': 'جاری',
  'change': 'تبدیل',
  'turn': 'موڑنا',
  'open': 'کھولنا',
  'close': 'بند',
  'meet': 'ملنا',
  'follow': 'پیروی',
  'call': 'بلانا',
  'talk': 'بات',
  'discuss': 'بحث',
  
  // Common nouns
  'time': 'وقت',
  'day': 'دن',
  'night': 'رات',
  'week': 'ہفتہ',
  'month': 'مہینہ',
  'year': 'سال',
  'hour': 'گھنٹہ',
  'minute': 'منٹ',
  'second': 'سیکنڈ',
  'morning': 'صبح',
  'afternoon': 'دوپہر',
  'evening': 'شام',
  'today': 'آج',
  'tomorrow': 'کل',
  'yesterday': 'کل',
  'person': 'شخص',
  'people': 'لوگ',
  'man': 'آدمی',
  'woman': 'عورت',
  'child': 'بچہ',
  'boy': 'لڑکا',
  'girl': 'لڑکی',
  'family': 'خاندان',
  'friend': 'دوست',
  'house': 'گھر',
  'home': 'گھر',
  'place': 'جگہ',
  'world': 'دنیا',
  'country': 'ملک',
  'city': 'شہر',
  'town': 'قصبہ',
  'area': 'علاقہ',
  'school': 'سکول',
  'university': 'یونیورسٹی',
  'college': 'کالج',
  'office': 'دفتر',
  'company': 'کمپنی',
  'business': 'کاروبار',
  'government': 'حکومت',
  'money': 'پیسہ',
  'food': 'کھانا',
  'water': 'پانی',
  'book': 'کتاب',
  'paper': 'کاغذ',
  'car': 'گاڑی',
  'phone': 'فون',
  'computer': 'کمپیوٹر',
  'internet': 'انٹرنیٹ',
  'website': 'ویب سائٹ',
  'information': 'معلومات',
  'news': 'خبریں',
  'story': 'کہانی',
  'problem': 'مسئلہ',
  'question': 'سوال',
  'answer': 'جواب',
  'idea': 'خیال',
  'way': 'راستہ',
  'method': 'طریقہ',
  'system': 'نظام',
  'service': 'خدمت',
  'product': 'پروڈکٹ',
  'result': 'نتیجہ',
  'effect': 'اثر',
  'reason': 'وجہ',
  'cause': 'سبب',
  'purpose': 'مقصد',
  'goal': 'ہدف',
  'plan': 'منصوبہ',
  'project': 'پروجیکٹ',
  'program': 'پروگرام',
  'research': 'تحقیق',
  'analysis': 'تجزیہ',
  'report': 'رپورٹ',
  'data': 'ڈیٹا',
  'technology': 'ٹیکنالوجی',
  'science': 'سائنس',
  'health': 'صحت',
  'education': 'تعلیم',
  'culture': 'ثقافت',
  'language': 'زبان',
  'art': 'فن',
  'music': 'موسیقی',
  'sport': 'کھیل',
  'film': 'فلم',
  'photo': 'تصویر',
  
  // Common adjectives
  'good': 'اچھا',
  'bad': 'برا',
  'big': 'بڑا',
  'small': 'چھوٹا',
  'large': 'بڑا',
  'little': 'چھوٹا',
  'long': 'لمبا',
  'short': 'چھوٹا',
  'high': 'اونچا',
  'low': 'نیچا',
  'new': 'نیا',
  'old': 'پرانا',
  'young': 'جوان',
  'early': 'جلدی',
  'late': 'دیر',
  'fast': 'تیز',
  'slow': 'آہستہ',
  'hot': 'گرم',
  'cold': 'ٹھنڈا',
  'warm': 'گرم',
  'cool': 'ٹھنڈا',
  'easy': 'آسان',
  'difficult': 'مشکل',
  'hard': 'مشکل',
  'simple': 'آسان',
  'complex': 'پیچیدہ',
  'important': 'اہم',
  'special': 'خاص',
  'common': 'عام',
  'popular': 'مقبول',
  'famous': 'مشہور',
  'local': 'مقامی',
  'national': 'قومی',
  'international': 'بین الاقوامی',
  'public': 'عوامی',
  'private': 'نجی',
  'free': 'مفت',
  'available': 'دستیاب',
  'possible': 'ممکن',
  'impossible': 'ناممکن',
  'necessary': 'ضروری',
  'different': 'مختلف',
  'same': 'ویسا',
  'similar': 'ملتا جلتا',
  'beautiful': 'خوبصورت',
  'nice': 'اچھا',
  'great': 'بہترین',
  'excellent': 'بہترین',
  'perfect': 'کامل',
  'correct': 'صحیح',
  'wrong': 'غلط',
  'true': 'سچ',
  'false': 'جھوٹ',
  'real': 'حقیقی',
  'right': 'صحیح',
  'left': 'بائیں',
  'full': 'بھرا',
  'empty': 'خالی',
  'opened': 'کھلا',
  'closed': 'بند',
  'clear': 'صاف',
  'dark': 'اندھیرا',
  'light': 'روشنی',
  'heavy': 'بھاری',
  'strong': 'مضبوط',
  'weak': 'کمزور',
  'safe': 'محفوظ',
  'dangerous': 'خطرناک',
  'clean': 'صاف',
  'dirty': 'گندا',
  'healthy': 'صحت مند',
  'sick': 'بیمار',
  'rich': 'امیر',
  'poor': 'غریب',
  'expensive': 'مہنگا',
  'cheap': 'سستا',
  'modern': 'جدید',
  'traditional': 'روایتی',
  'normal': 'عام',
  'natural': 'قدرتی',
  'artificial': 'مصنوعی',
  'digital': 'ڈیجیٹل',
  'online': 'آن لائن',
  'social': 'سماجی',
  'political': 'سیاسی',
  'economic': 'اقتصادی',
  'financial': 'مالی',
  'medical': 'طبی',
  'legal': 'قانونی',
  'personal': 'ذاتی',
  'professional': 'پیشہ ورانہ',
  'academic': 'تعلیمی',
  'technical': 'تکنیکی',
  'scientific': 'سائنسی',
  'historical': 'تاریخی',
  'cultural': 'ثقافتی',
  'environmental': 'ماحولیاتی',
  'global': 'عالمی',
  'regional': 'علاقائی',
  
  // Technology & Internet
  'software': 'سافٹ ویئر',
  'hardware': 'ہارڈ ویئر',
  'application': 'ایپلیکیشن',
  'database': 'ڈیٹابیس',
  'server': 'سرور',
  'network': 'نیٹ ورک',
  'security': 'سیکیورٹی',
  'password': 'پاس ورڈ',
  'username': 'صارف نام',
  'email': 'ای میل',
  'download': 'ڈاؤن لوڈ',
  'upload': 'اپ لوڈ',
  'browser': 'براؤزر',
  'search': 'تلاش',
  'click': 'کلک',
  'type': 'ٹائپ',
  'save': 'محفوظ',
  'delete': 'حذف',
  'copy': 'کاپی',
  'paste': 'پیسٹ',
  'edit': 'ترمیم',
  'create': 'تخلیق',
  'update': 'اپ ڈیٹ',
  'install': 'انسٹال',
  'remove': 'ہٹانا',
  'connect': 'جڑنا',
  'disconnect': 'منقطع',
  'sync': 'ہم آہنگ',
  'backup': 'بیک اپ',
  'restore': 'بحالی',
  'format': 'فارمیٹ',
  'compress': 'کمپریس',
  'extract': 'نکالنا',
  'encrypt': 'خفیہ کرنا',
  'decrypt': 'رمز کشائی',
  'algorithm': 'الگورتھم',
  'function': 'فنکشن',
  'variable': 'متغیر',
  'array': 'صف',
  'object': 'آبجیکٹ',
  'string': 'سٹرنگ',
  'number': 'نمبر',
  'boolean': 'بولین',
  'null': 'خالی',
  'undefined': 'غیر واضح',
  'error': 'خرابی',
  'warning': 'انتباہ',
  'success': 'کامیابی',
  'failure': 'ناکامی',
  'loading': 'لوڈنگ',
  'processing': 'پروسیسنگ',
  'complete': 'مکمل',
  'incomplete': 'نامکمل',
  'valid': 'درست',
  'invalid': 'غلط',
  'required': 'ضروری',
  'optional': 'اختیاری',
  'default': 'طے شدہ',
  'custom': 'کسٹم',
  
  // Business & Economics  
  'market': 'بازار',
  'economy': 'معیشت',
  'finance': 'مالیات',
  'investment': 'سرمایہ کاری',
  'profit': 'منافع',
  'loss': 'نقصان',
  'revenue': 'آمدنی',
  'expense': 'خرچ',
  'budget': 'بجٹ',
  'cost': 'لاگت',
  'price': 'قیمت',
  'value': 'قدر',
  'worth': 'مالیت',
  'asset': 'اثاثہ',
  'liability': 'ذمہ داری',
  'debt': 'قرض',
  'credit': 'ادھار',
  'loan': 'قرضہ',
  'interest': 'سود',
  'bank': 'بینک',
  'account': 'کھاتہ',
  'transaction': 'لین دین',
  'payment': 'ادائیگی',
  'receipt': 'رسید',
  'invoice': 'بل',
  'contract': 'معاہدہ',
  'agreement': 'اتفاق',
  'deal': 'ڈیل',
  'negotiation': 'بات چیت',
  'proposal': 'تجویز',
  'offer': 'پیشکش',
  'demand': 'مانگ',
  'supply': 'سپلائی',
  'customer': 'گاہک',
  'client': 'کلائنٹ',
  'supplier': 'سپلائر',
  'vendor': 'فروخت کنندہ',
  'competitor': 'حریف',
  'partner': 'شریک',
  'investor': 'سرمایہ کار',
  'shareholder': 'حصہ دار',
  'employee': 'ملازم',
  'employer': 'آجر',
  'manager': 'منیجر',
  'director': 'ڈائریکٹر',
  'executive': 'ایگزیکٹو',
  'chairman': 'چیئرمین',
  'president': 'صدر',
  'secretary': 'سیکریٹری',
  'assistant': 'معاون',
  'consultant': 'مشیر',
  'advisor': 'مشورہ دینے والا',
  'analyst': 'تجزیہ کار',
  'specialist': 'ماہر',
  'expert': 'ماہر',
  'skilled': 'ہنر مند',
  'experienced': 'تجربہ کار',
  'qualified': 'اہل',
  'certified': 'تصدیق شدہ',
  'licensed': 'لائسنس یافتہ',
  'registered': 'رجسٹرڈ',
  'authorized': 'مجاز',
  'approved': 'منظور شدہ',
  'verified': 'تصدیق شدہ',
  'confirmed': 'تصدیق شدہ',
  'accepted': 'قبول شدہ',
  'rejected': 'مسترد',
  'pending': 'زیر التواء',
  'reviewing': 'جائزہ',
  'evaluating': 'تشخیص',
  'analyzing': 'تجزیہ',
  'investigating': 'تحقیق',
  'researching': 'تحقیق',
  'developing': 'ترقی',
  'improving': 'بہتری',
  'enhancing': 'اضافہ',
  'optimizing': 'بہتر بنانا',
  'maximizing': 'زیادہ سے زیادہ',
  'minimizing': 'کم سے کم',
  'reducing': 'کم کرنا',
  'increasing': 'بڑھانا',
  'expanding': 'پھیلانا',
  'growing': 'بڑھنا',
  'declining': 'کم ہونا',
  'falling': 'گرنا',
  'rising': 'اٹھنا',
  'stable': 'مستحکم',
  'steady': 'مستقل',
  'consistent': 'مستقل',
  'reliable': 'قابل اعتماد',
  'dependable': 'بھروسہ مند',
  'trustworthy': 'قابل اعتماد',
  'honest': 'ایمان دار',
  'fair': 'منصفانہ',
  'ethical': 'اخلاقی',
  'moral': 'اخلاقی',
  'responsible': 'ذمہ دار',
  'accountable': 'جواب دہ',
  'transparent': 'شفاف',
  'obvious': 'واضح',
  'evident': 'ظاہر',
  'apparent': 'نمایاں',
  'visible': 'نظر آنے والا',
  'hidden': 'چھپا ہوا',
  'secret': 'خفیہ',
  'confidential': 'رازدارانہ',
  'individual': 'انفرادی',
  'collective': 'اجتماعی',
  'group': 'گروپ',
  'team': 'ٹیم',
  'organization': 'تنظیم',
  'institution': 'ادارہ',
  'association': 'انجمن',
  'society': 'معاشرہ',
  'community': 'کمیونٹی',
  'population': 'آبادی',
  'citizen': 'شہری',
  'resident': 'رہائشی',
  'inhabitant': 'باشندہ',
  'native': 'مقامی',
  'foreigner': 'غیر ملکی',
  'immigrant': 'مہاجر',
  'refugee': 'پناہ گزین',
  'visitor': 'زائر',
  'tourist': 'سیاح',
  'traveler': 'مسافر',
  'passenger': 'مسافر',
  'driver': 'ڈرائیور',
  'pilot': 'پائلٹ',
  'captain': 'کپتان',
  'crew': 'عملہ',
  'staff': 'عملہ',
  'personnel': 'اہلکار',
  'workforce': 'افرادی قوت',
  'labor': 'مزدوری',
  'worker': 'مزدور',
  'technician': 'ٹیکنیشن',
  'engineer': 'انجینئر',
  'architect': 'معمار',
  'designer': 'ڈیزائنر',
  'artist': 'فن کار',
  'musician': 'موسیقار',
  'singer': 'گلوکار',
  'actor': 'اداکار',
  'actress': 'اداکارہ',
  'writer': 'لکھاری',
  'author': 'مصنف',
  'journalist': 'صحافی',
  'reporter': 'رپورٹر',
  'editor': 'ایڈیٹر',
  'publisher': 'ناشر',
  'translator': 'مترجم',
  'interpreter': 'مترجم',
  'teacher': 'استاد',
  'professor': 'پروفیسر',
  'student': 'طالب علم',
  'scholar': 'عالم',
  'researcher': 'محقق',
  'scientist': 'سائنس دان',
  'doctor': 'ڈاکٹر',
  'nurse': 'نرس',
  'patient': 'مریض',
  'lawyer': 'وکیل',
  'judge': 'جج',
  'police': 'پولیس',
  'officer': 'افسر',
  'soldier': 'سپاہی',
  'general': 'جنرل',
  'minister': 'وزیر',
  'politician': 'سیاست دان',
  'leader': 'رہنما',
  'follower': 'پیروکار',
  'supporter': 'حامی',
  'opponent': 'مخالف',
  'enemy': 'دشمن',
  'colleague': 'ساتھی',
  'neighbor': 'پڑوسی',
  'relative': 'رشتہ دار',
  'father': 'والد',
  'mother': 'والدہ',
  'parent': 'والدین',
  'son': 'بیٹا',
  'daughter': 'بیٹی',
  'brother': 'بھائی',
  'sister': 'بہن',
  'husband': 'شوہر',
  'wife': 'بیوی',
  'grandfather': 'دادا',
  'grandmother': 'دادی',
  'uncle': 'چچا',
  'aunt': 'چچی',
  'cousin': 'کزن',
  'nephew': 'بھتیجا',
  'niece': 'بھتیجی',
  
  // Daily Life & Actions
  'wake': 'جاگنا',
  'rest': 'آرام',
  'relax': 'آرام کرنا',
  'exercise': 'ورزش',
  'workout': 'ورزش',
  'jump': 'کودنا',
  'swim': 'تیرنا',
  'dance': 'رقص',
  'sing': 'گانا',
  'laugh': 'ہنسنا',
  'cry': 'رونا',
  'smile': 'مسکرانا',
  'frown': 'بھونہیں چڑھانا',
  'angry': 'غصہ',
  'happy': 'خوش',
  'sad': 'اداس',
  'excited': 'پرجوش',
  'nervous': 'گھبرایا ہوا',
  'calm': 'پرسکون',
  'worried': 'پریشان',
  'confused': 'حیران',
  'surprised': 'حیران',
  'shocked': 'صدمہ',
  'scared': 'ڈرا ہوا',
  'brave': 'بہادر',
  'confident': 'پراعتماد',
  'shy': 'شرمیلا',
  'proud': 'فخر',
  'ashamed': 'شرمندہ',
  'guilty': 'قصوروار',
  'innocent': 'بے قصور',
  'polite': 'مہذب',
  'rude': 'بدتمیز',
  'kind': 'مہربان',
  'cruel': 'ظالم',
  'generous': 'فیاض',
  'selfish': 'خودغرض',
  'impatient': 'بے صبر',
  'careful': 'محتاط',
  'careless': 'لاپرواہ',
  'serious': 'سنجیدہ',
  'funny': 'مضحکہ خیز',
  'boring': 'بورنگ',
  'interesting': 'دلچسپ',
  'exciting': 'دلچسپ',
  'amazing': 'حیرت انگیز',
  'wonderful': 'حیرت انگیز',
  'terrible': 'خوفناک',
  'awful': 'بہت برا',
  'outstanding': 'شاندار',
  'fantastic': 'شاندار',
  'brilliant': 'شاندار',
  'genius': 'ذہین',
  'intelligent': 'ذہین',
  'smart': 'ہوشیار',
  'clever': 'چالاک',
  'wise': 'دانا',
  'foolish': 'احمق',
  'stupid': 'بے وقوف',
  'ignorant': 'جاہل',
  'educated': 'تعلیم یافتہ',
  'knowledgeable': 'علم والا',
  'talented': 'باصلاحیت',
  'creative': 'تخلیقی',
  'artistic': 'فنکارانہ',
  'musical': 'موسیقی',
  'athletic': 'کھیل کود',
  
  // Time & Dates
  'decade': 'دہائی',
  'century': 'صدی',
  'millennium': 'ہزار سال',
  'moment': 'لمحہ',
  'instant': 'فوری',
  'period': 'مدت',
  'duration': 'مدت',
  'temporary': 'عارضی',
  'permanent': 'مستقل',
  'forever': 'ہمیشہ',
  'never': 'کبھی نہیں',
  'always': 'ہمیشہ',
  'sometimes': 'کبھی کبھی',
  'often': 'اکثر',
  'rarely': 'شاذ و نادر',
  'frequently': 'اکثر',
  'occasionally': 'کبھی کبھار',
  'daily': 'روزانہ',
  'weekly': 'ہفتہ وار',
  'monthly': 'ماہانہ',
  'yearly': 'سالانہ',
  'hourly': 'گھنٹہ وار',
  'midnight': 'آدھی رات',
  'noon': 'دوپہر',
  'dawn': 'فجر',
  'dusk': 'شام',
  'sunrise': 'طلوع آفتاب',
  'sunset': 'غروب آفتاب',
  'past': 'ماضی',
  'present': 'حال',
  'future': 'مستقبل',
  'recent': 'حالیہ',
  'current': 'موجودہ',
  'upcoming': 'آنے والا',
  'previous': 'پچھلا',
  'next': 'اگلا',
  'first': 'پہلا',
  'last': 'آخری',
  'final': 'حتمی',
  'initial': 'ابتدائی',
  'beginning': 'شروعات',
  'middle': 'درمیان',
  'center': 'مرکز',
  'edge': 'کنارہ',
  'corner': 'کونا',
  'side': 'طرف',
  'top': 'اوپر',
  'bottom': 'نیچے',
  'front': 'سامنے',
  'back': 'پیچھے',
  'inside': 'اندر',
  'outside': 'باہر',
  'above': 'اوپر',
  'below': 'نیچے',
  'over': 'اوپر',
  'under': 'نیچے',
  'between': 'درمیان',
  'among': 'میں سے',
  'around': 'چاروں طرف',
  'through': 'کے ذریعے',
  'across': 'پار',
  'along': 'ساتھ ساتھ',
  'towards': 'کی طرف',
  'away': 'دور',
  'near': 'قریب',
  'far': 'دور',
  'distant': 'دور',
  'here': 'یہاں',
  'there': 'وہاں',
  'where': 'کہاں',
  'everywhere': 'ہر جگہ',
  'nowhere': 'کہیں نہیں',
  'somewhere': 'کہیں',
  'anywhere': 'کہیں بھی',
  
  // Colors & Appearance
  'color': 'رنگ',
  'red': 'لال',
  'blue': 'نیلا',
  'green': 'ہرا',
  'yellow': 'پیلا',
  'orange': 'نارنجی',
  'purple': 'جامنی',
  'pink': 'گلابی',
  'brown': 'بھورا',
  'black': 'کالا',
  'white': 'سفید',
  'gray': 'سرمئی',
  'grey': 'سرمئی',
  'bright': 'چمکدار',
  'pale': 'ہلکا',
  'vivid': 'چمکدار',
  'dull': 'بے رنگ',
  'shiny': 'چمکدار',
  'matte': 'میٹ',
  'opaque': 'غیر شفاف',
  'thick': 'موٹا',
  'thin': 'پتلا',
  'wide': 'چوڑا',
  'narrow': 'تنگ',
  'broad': 'چوڑا',
  'tight': 'تنگ',
  'loose': 'ڈھیلا',
  'smooth': 'ہموار',
  'rough': 'کھردرا',
  'soft': 'نرم',
  'sharp': 'تیز',
  'blunt': 'کند',
  'pointed': 'نوکیلا',
  'round': 'گول',
  'square': 'مربع',
  'circular': 'دائرہ',
  'oval': 'بیضوی',
  'straight': 'سیدھا',
  'curved': 'خمیدہ',
  'bent': 'مڑا ہوا',
  'flat': 'ہموار',
  'steep': 'کھڑا',
  'level': 'برابر',
  'uneven': 'غیر برابر',
  'balanced': 'متوازن',
  'unbalanced': 'غیر متوازن',
  'equal': 'برابر',
  'unequal': 'غیر برابر',
  'opposite': 'مخالف',
  'reverse': 'الٹ',
  'forward': 'آگے',
  'backward': 'پیچھے',
  'upward': 'اوپر کی طرف',
  'downward': 'نیچے کی طرف'
};

export function translateToUrdu(text: string): string {
  // Split text into words and translate each word
  const words = text.toLowerCase().match(/\b\w+\b/g) || [];
  const translatedWords = words.map(word => {
    return englishToUrduDict[word] || word;
  });
  
  // Join translated words back together
  let translatedText = translatedWords.join(' ');
  
  // Keep original punctuation structure roughly
  const punctuation = text.match(/[.,!?;:()]/g) || [];
  punctuation.forEach((punct, index) => {
    if (index < translatedWords.length) {
      translatedText += punct;
    }
  });
  
  return translatedText;
} 